services:
    indicadorchileapi:
        image: ${DOCKER_REGISTRY-}indicadorchileapi
        build:
            context: .
            dockerfile: IndicadorChileAPI/Dockerfile
        environment:
            - TZ=America/Santiago