version: "3.9"

services:
    api:
        image: ${DOCKER_REGISTRY-}api
        restart: always
        build:
            context: .
            dockerfile: API/Dockerfile
        ports:
            - "8080"
            - "8081"
        environment:
            # Time Zone
            - TZ=America/Santiago
            # Idioma
            - LANG=es_CL.UTF-8
            - LANGUAGE=es_CL:es
            - LC_ALL=es_CL.UTF-8