version: '1.0'

services:
    time-zone:
        build: .
        ports:
            - "8080:80"
        environment:
            # Establece la variable de entorno para la zona horaria
            - TZ=America/Santiago
        volumes:
            # Monta los archivos de configuración de zona horaria desde el host
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro