version: "3.8"

services:
    indicadorchileapi:
        image: ${DOCKER_REGISTRY-}indicadorchileapi
        restart: always
        build:
            context: .
            dockerfile: IndicadorChileAPI/Dockerfile
        environment:
            - TZ=America/Santiago
            - LANG=es_CL.UTF-8
            - LANGUAGE=es_CL:es
            - LC_ALL=es_CL.UTF-8